---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 19:28
---

--Lua应用
LuaAPP = LuaAPP or {}
local this = LuaAPP

--初始化
function this:Init()
    self:RegisterStates()
    self:ChangeState(StateNames.InitState)
end

--注册所有状态
function this:RegisterStates()
    stateMap = {}
    for key, value in pairs(StateNames or {}) do
        stateMap[value] = require(value).new()
    end
end

--获取状态
function this:GetState(stateName)
    return stateMap[stateName]
end

--切换状态
function this:ChangeState(stateName)
    local state = stateMap[stateName]
    if state ~= nil then
        if this.curState~=nil then
            this.curState.Exit()
        end
        this.curState = state
        this.curState.Enter()
    else
        LogError("change state error:"..stateName.."is nil")
    end
end