---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 19:28
---

--Lua应用
LuaAPP = LuaAPP or {}

--初始化
function LuaAPP.Init()
    LuaAPP.RegisterStates()
    LuaAPP.ChangeState(StateNames.InitState)
end

--注册所有状态
function LuaAPP.RegisterStates()
    stateMap = {}
    for key, value in pairs(StateNames or {}) do
        stateMap[value] = require(value).new()
    end
end

--获取状态
function LuaAPP.GetState(stateName)
    return stateMap[stateName]
end

--切换状态
function LuaAPP.ChangeState(stateName)
    local state = stateMap[stateName]
    if state ~= nil then
        if LuaAPP.curState~=nil then
            LuaAPP.curState.Exit()
        end
        LuaAPP.curState = state
        LuaAPP.curState:Enter()
    else
        LogError(stateName)
    end
end