---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/26 17:27
---
Alert = class("Alert", WindowBase)
local this = Alert

function this:OnWDAwake(uiObj)
    self.UIObj = uiObj
    self:BindWindow(uiObj)
    self:AddButtonEvent()
end

function this:BindWindow(uiObj)
    self.SureButton = LuaUtil.GetChildComponent(uiObj,"root/SureButton",ComponentName.UIButton)
    self.CancelButton = LuaUtil.GetChildComponent(uiObj,"root/CancelButton",ComponentName.UIButton)
    self.Tips = LuaUtil.GetChildComponent(uiObj,"root/Tips",ComponentName.UIText)
end

function this:AddButtonEvent()
    self.SureButton.onClick:AddListener(function() self:SureEvent() end)
    self.CancelButton.onClick:AddListener(function() self:CancelEvent() end)
end

function this:OnWDStart(param)
    self.action = param[1]
    self.Tips.text = param[2]
end

function this:SureEvent()
    self:FinishWindow()
    if self.action ~= nil then
        self.action()
    end
end

function this:CancelEvent()
    self:FinishWindow()
end

function this:IsStatic()
    return false
end

return this