---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/24 22:25
---

CreateRoleWindow = class("CreateRoleWindow",UIBase)
local this = CreateRoleWindow

function this:InitUI(uiObj)
    self.UIObj = uiObj
    self:BindWindow(uiObj)
    self:AddButtonEvent()
end

function this:BindWindow(uiObj)
    --self.headStyle = Util.GetChildComponent(root,"headStyle",1)
    self.ReturnButton = Util.GetChildComponent(uiObj,"root/ReturnButton",3)
end

function this:AddButtonEvent()
    self.ReturnButton.onClick:AddListener(function ()self:ReturnEvent() end)
end
function this:ReturnEvent()
    LuaAPP.GetUIManager():CloseWindow("CreateRoleWindow","")
end
function this:Update()
    Log("MainWindow Update")
end

function this:GetUIType()
    return UIType.FullType
end

return this