---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/24 19:06
---
LoginWindow = class("LoginWindow", WindowBase)

local this = LoginWindow

function this:InitUI(uiObj)
    self.UIObj = uiObj
    self:BindWindow(uiObj)
    self:AddButtonEvent()
    Log("LoginWindow InitUI")
end

function this:BindWindow(uiObj)
    self.TimeLabel = Util.GetChildComponent(uiObj,"root/time",ComponentName.Text)
    self.LoginButton = Util.GetChildComponent(uiObj,"root/LoginButton",ComponentName.UIButton)
    self.back = Util.GetChildComponent(uiObj,"back",ComponentName.UIRawImage)
end

function this:AddButtonEvent()
    self.LoginButton.onClick:AddListener(function() self:LoginEvent() end)
end

function this:LoginEvent()
    LuaAPP.GetUIManager():OpenWindow("Alert","")
end

function this:OnEnableUI(param)
    self.timer = self:NewTimer()
    self.timer:AddOnTimer(function () self:UpdateTime() end)
    self.timer:Start(true)
    self.back:LoadImage()
    --self.back:SetGray(true)
    self.LoginButton:SetGray(true)
end

function this:UpdateTime()
    self.TimeLabel.text = Util.TimeToString_02(Time.GetTimestamp())
end

function this:Update()
    --self.TimeLabel.text = Util.TimeToString_02(Time.GetTimestamp())
end

function this:GetUILayer()
    return WindowLayer.MiddleStatic
end
function this:GetUIType()
    return WindowType.FullType
end
return this

