---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/9 10:37
--- 更新驱动

UpdateDriver = class("UpdateDriver", WindowBase)

local this = UpdateDriver

function this:InitUI(uiObj)
    self.UIObj = uiObj
    self:BindWindow(uiObj)
    self:AddButtonEvent()
end

function this:BindWindow(uiObj)
    self.tips = LuaUtil.GetChildComponent(uiObj, "root/tips", ComponentName.UIText)
    self.slider = LuaUtil.GetChildComponent(uiObj, "root/Slider", ComponentName.slider)
    self.version = LuaUtil.GetChildComponent(uiObj, "root/version", ComponentName.UIText)
end

function this:AddButtonEvent()
    LuaAPP.GetGlobalEvent():AddEvent(EventName.UpdateDriverSetValue,
            function(step, process, curLoadSize, totalLoadSize)
                self:SetValue(step, process, curLoadSize, totalLoadSize)
            end)
    LuaAPP.GetGlobalEvent():AddEvent(EventName.UpdateDriverSetTips,
            function(tips)
                self:SetTips(tips)
            end)
end

function this:OnEnableUI()
    self.slider.value = 0
    self.tips.text = Language.TIP_0
    self.version.text = Language.Get(Language.Version, SDKHelper.getAppVersion().version)
    LuaAPP.GetBackGroundManager():Change("loginBack_3")
end

function this:SetTips(tips)
    self.tips.text = tips
end

function this:SetValue(step, process, curLoadSize, totalLoadSize)
    local tip = ""
    if process < 0 then
        return
    end
    if step == UpdateStep.CheckVersion then
        tip = Language.UpdateDriver_03
    elseif step == UpdateStep.GetUpdateList then
        tip = Language.UpdateDriver_05
    elseif step == UpdateStep.CompareData then
        tip = Language.UpdateDriver_05
    elseif step == UpdateStep.MakeSureDownload then
        tip = Language.Get(Language.UpdateDriver_06, curLoadSize, totalLoadSize)
    elseif step == UpdateStep.DownloadData then
    elseif step == UpdateStep.CheckData then
        tip = Language.UpdateDriver_07
    elseif step == UpdateStep.CopyData then
        tip = Language.UpdateDriver_08
    elseif step == UpdateStep.CleanCache then
    elseif step == UpdateStep.Finish then
        tip = Language.UpdateDriver_09
    end
    self.tips.text = tip
    self.slider.value = step
end

function this:GetUIType()
    return WindowType.FullType
end

return this