---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 16:10
---
--引入全局表定义
require(ModulePath.GlobalDefine)
--引入lua Class
require(ModulePath.DefinitionClass)
--引入UI管理器
require(ModulePath.UIManager)
--引入背景管理器
require(ModulePath.BackGroundManager)
--引入lua APP
require(ModulePath.LuaAPP)
--引入UIBase
require(ModulePath.UIBase)
--引入窗口基类
require(ModulePath.WindowBase)
--引入有序列表
require(ModulePath.YMList)
--引入字典
require(ModulePath.YMDictionary)
--引入定时器
require(ModulePath.Timer)
--引入定时器管理器
require(ModulePath.TimerManager)
--引入语言表
require(ModulePath.Language)
--引入Lua工具
require(ModulePath.LuaUtil)
--引入事件系统
require(ModulePath.YMEvent)
--引入状态步骤
require(ModulePath.StateStepDefine)

GameObject = UnityEngine.GameObject
WWW = UnityEngine.WWW
Util = LuaFramework.Core.Util
Application = UnityEngine.Application
NetworkReachability = UnityEngine.NetworkReachability
PlayerPrefs = PlayerPrefs
GameManager = LuaHelper.GetGameManager()
ResUpdateManager = LuaHelper.GetResourceUpdateManager()
CoroutineCenter = LuaHelper.GetCoroutineCenter()
CertifyManager = LuaHelper.GetCertifyManager()
ServerManager = LuaHelper.GetServerManager()

---#全局方法定义#--
--日志打印
Log = function(m)
    local traceBack = string.split(debug.traceback("",2),"\n")
    local logStr = tostring(m).."\n"
    for i = 3, #traceBack do
        logStr = logStr..traceBack[i].."\n"
    end
    Util.Log(logStr)
end
--警告日志打印
LogWarn = function(w)
    local traceback = string.split(debug.traceback("", 2), "\n")
    Util.LogWarning(traceback[3].."\n"..tostring(w))
end
--错误日志打印
LogError = function(e)
    local traceback = string.split(debug.traceback("", 2), "\n")
    local logStr = tostring(e).."\n";
    for i = 3, #traceback do
        logStr = logStr..traceback[i].."\n";
    end
    Util.LogError(logStr);
end