---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/17 16:44
--- 玩家参数

PlayerSetting = {
    UID = "uid",
    ServerIP = "serverIP",
    ServerID = "serverID",
}