---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/17 14:39
--- 公告
local cjson = require "cjson"

local Affiche = class("Affiche")
local this = Affiche

function this:jsonRead(node)
    local data = cjson.decode(node)
    self.id = tonumber(data["id"])
    self.title = tostring(data["title"])
    self.content = tostring(data["content"])
    self.startTime = tonumber(data["startTime"])
    self.endTime = tonumber(data["endTime"])
    self.order = tonumber(data["order"])
end

--设置id
function this:setId(id)
    self.id = id
end

--设置内容
function this:setContent(content)
    self.content = content
end

--设置标题
function this:setTitle(title)
    self.title = title
end

--设置开始时间
function this:setStartTime(startTime)
    self.startTime = startTime
end

--设置结束时间
function this:setEndTime(endTime)
    self.endTime = endTime
end

--设置顺序
function this:setOrder(order)
    self.order = order

end

return this