---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/17 16:01
--- 公告窗口

AfficheWindow = class("AfficheWindow",WindowBase)
local this = AfficheWindow
function this:InitUI(uiObj)
    self.UIObj = uiObj
    self:BindWindow(uiObj)
    self:AddButtonEvent()
end

function this:BindWindow(uiObj)

end

function this:AddButtonEvent()

end

function this:OnEnableUI(param)
    self.affiches = param[1]
    self.destroyAction = param[2]
end

function this:IsStatic()
    return false
end

return this
