---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/21 17:24
---
require("Define/Define")

--Lua端主入口，从这里开始lua逻辑
function Main()
    LuaAPP.Init()
    LuaAPP.ChangeState(StateNames.LoginState)
end
--检查更新
function CheckVersionUpdate()
    LuaAPP.Init()
    LuaAPP.ChangeState(StateNames.CheckVersionState)
end

--显示Alert
function ShowAlert(msg,callback,changeBack)
    LuaAPP.GetUIManager():Init()
    if changeBack~=nil and changeBack == true then
        local backManger = LuaAPP:GetBackGroundManager()
        backManger:Init()
        backManger:Change("loginBack_3")
    end
    LuaAPP.GetUIManager():OpenWindow(WindowName.Alert,
            function()
                if callback~=nil then
                    callback()
                end
            end, Language.Get(msg))
end

--切换场景通知
function OnLevelWasLoad(level)
    collectgarbage("collect")
    Time.timeSinceLevelLoad = 0
end