---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/11 12:12
--- 配置管理器

ConfigManager = class("ConfigManager")
local this = ConfigManager

--初始化配置
function this:InitConfig(callback)
    --这里做一些配置初始化的相关操作
    if callback~=nil then
        callback()
    end
end
return this
