---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/29 19:46
--- 定时器管理器

TimerManager = class("TimerManager")

function TimerManager:ctor()
    self.timerList = YMList:New('table')
end

--定时更新
function TimerManager:Update()
    local nowTime = Time.GetTimestamp()
    for i = self.timerList:Count(), 1,-1 do
        if self.timerList[i]:IsDispose() then
            self.timerList:RemoveAt(i)
        else
            self.timerList[i]:Update(nowTime)
        end
    end
end

--添加定时器
function TimerManager:AddTimer(timer)
    if not self.timerList:Contains(timer) then
        self.timerList:Add(timer)
    end
end

function TimerManager:GetTimer(intervalTime)
    local timer = Timer.new()
    timer:InitTimer(intervalTime,0)
    if self.timerList == nil then
        self.timerList = YMList:New('table')
    end
    self.timerList:Add(timer)
    return timer
end

--清空定时器
function TimerManager:Clear()
    self.timerList:Clear()
end

return TimerManager