---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/29 19:46
--- 定时器管理器

TimerManager = class("TimerManager")

function TimerManager:ctor()
    self.timerList = YMList:New('table')
end

function TimerManager:Update()
    --Log("TimerManager Update")
    local nowTime = Time.GetTimestamp()
    Log(self.timerList:Count())
    for i = self.timerList:Count(), 1,-1 do
        Log("update")
        if self.timerList[i]:IsDispose() then
            self.timerList[i]:RemoveAt(i)
        else
            self.timerList[i]:Update(nowTime)
        end
    end
end

function TimerManager:AddTimer(timer)
    if not self.timerList:Contains(timer) then
        self.timerList:Add(timer)
    end
end

return TimerManager