---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/8 20:47
--- 检查更新状态

require("State/BaseState")

local CheckUpdateState = class("CheckUpdateState",BaseState)
local this = CheckUpdateState

function this:Enter()

end


function this:Update()

end

function this:Exit()

end

return this