---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/8 20:47
--- 检查版本更新状态

require("State/BaseState")

local CheckVersionState = class("CheckVersionState",BaseState)
local this = CheckVersionState

function this:Enter()
    LuaAPP.GetUIManager():OpenWindow(WindowName.UpdateDriver)
    if Application.internetReachability == NetworkReachability.NotReachable then
        LuaAPP.GetUIManager():OpenWindow(WindowName.Alert,
            function ()
                ResourceUpdateManager.Connect()
            end,Language.network_01)
    else
        ResourceUpdateManager.Connect()
    end
end


function this:Update()

end

function this:Exit()

end

return this