---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 14:47
---
require("State/BaseState")

local InitSate = class("InitSate",BaseState)
local this = InitSate

function this:Enter()
    LuaAPP.GetUIManager():Init()
    LuaAPP.GetBackGroundManager():Init()
end

function this:Update()

end

function this:Exit()

end

return this
