---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 14:47
---
require("State/BaseState")

local LoginState = class("LoginState",BaseState)
local this = LoginState

function this:Enter()
    self:InitManagers()
end

--初始化各类管理器
function this:InitManagers()
	
end

function this:Update()

end

function this:Exit()

end

return this
