---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 14:48
---
BaseState = class("BaseState")

local this = BaseState

---状态入口
function this:Enter()

end
---状态更新
function this:Update()

end
---状态退出
function this:Exit()

end
