---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/22 16:10
---
--引入lua Class
require("Common/DefinitionClass")
--引入UI管理器
require("Manager/UIManager")
--引入lua APP
require("LuaApp")
--引入UIBase
require("Base/UIBase")

---#全局变量定义#--
GameObject = UnityEngine.GameObject
WWW = UnityEngine.WWW
Util = LuaFrameworkCore.Util

--状态名称
StateNames = {
    InitState = "State/InitState",
    LoginState = "State/LoginState",
}
--UI层级 bottom{静态，动态} middle{静态，动态} top{静态，动态} 实现动静分离
UILayer = {
    BottomStatic = "_BottomStatic#",
    BottomDyn = "_BottomDyn#",
    MiddleStatic = "_MiddleStatic#",
    MiddleDyn = "_MiddleDyn",
    TopStatic = "_TopStatic#",
    TopDyn = "_TopDyn#",
}
--UI类型 普通， 全屏（关闭时均按返回处理）
UIType = {
    None = "None",
    FullType = "FullType",
}

---#全局方法定义#--
--日志打印
Log = function(m)
    local traceBack = string.split(debug.traceback("",2),"\n")
    local logStr = tostring(m).."\n"
    for i = 3, #traceBack do
        logStr = logStr..traceBack[i].."\n"
    end
    Util.Log(logStr)
end
--警告日志打印
LogWarn = function(w)
    local traceback = string.split(debug.traceback("", 2), "\n")
    Util.LogWarning(traceback[3].."\n"..tostring(w))
end
--错误日志打印
LogError = function(e)
    local traceback = string.split(debug.traceback("", 2), "\n")
    local logStr = tostring(e).."\n";
    for i = 3, #traceback do
        logStr = logStr..traceback[i].."\n";
    end
    Util.LogError(logStr);
end