---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/30 17:21
---这里存放了全局表的定义

--状态名称
StateNames = {
    InitState = "State/InitState",
    LoginState = "State/LoginState",
    CheckVersionState = "State/CheckVersionState",
}
--UI层级
WindowLayer = {
    --UI背景（底层）层
    CoreUIBG = "CoreUICanvas#/CoreUIBG#",
    --UI主要层级
    MainLayer = "CoreUICanvas#/CoreUILayer#/MainLayer",
    --UI顶层
    TopLayer = "CoreUICanvas#/CoreUILayer#/TopLayer",
    --UI最上层浮动层
    FloatingUILayer_T = "FloatingUILayer_T#",
    --与UICanvas同级的浮动层A order in layer：-100，最先渲染
    FloatingLayer_A = "FloatingLayer_A#",
    --与UICanvas同级的浮动层B order in layer：-100，在A之后渲染
    FloatingLayer_B = "FloatingLayer_B#",
    --与UICanvas同级的浮动层C order in layer：-100，在B之后渲染
    FloatingLayer_C = "FloatingLayer_C#",
}
--UI类型 普通， 全屏（关闭时均按返回处理）
WindowType = {
    None = "None",
    FullType = "FullType",
}
--组件名
ComponentName = {
    Image = 1,
    UIRawImage = 2,
    Button = 3,
    Text = 4,
    Mask = 5,
    Transform = 6,
    Toggle = 7,
    ToggleGroup = 8,
    Slider = 9,
    Scrollbar = 10,
    DropDown = 11,
    ScrollRect = 12,
    Selectable = 13,
    InputField = 14,
    RectTransform = 15,
    LayoutElement = 16,
    Outline = 17,
    Camera = 18,
    Animation = 19,
    UIButton = 20,
    UIImage = 21,
    UIText = 22,
}
--事件类型
EventName = {
    --LoginEvent 1-10
    LoginEvent1 = 1,
    LoginEvent2 = 2,
    --MainEvent 11-20
    MainEvent1 = 11,
    MainEvent2 = 12,
    --UpdateDriver 21-30
    UpdateDriverSetValue = 21,

}

--窗口名
WindowName = {
    LoginWindow = "LoginWindow",
    UpdateDriver = "UpdateDriver",
    CreateRoleWindow = "CreateRoleWindow",
    Alert = "Alert",
}
