---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/17 15:12
--- Lua端SDK帮助器

require("Common/YMList")
local Affiche = require("UI/Affiche/Affiche")

local SDKHelper = SDKHelper

LuaSDKHelper = {}
LuaSDKHelper.__Index = LuaSDKHelper

--获取所有公告
function LuaSDKHelper.getAffiches()
    local json = SDKHelper.platformHelper(HandlerConst.AFFICHE, nil)
    if json == nil or json == "" then
        return nil
    end
    local node = LuaSDKHelper.toJsonNode(json)
    local list = YMList:New('table')
    local nowTime = Time.GetTimestamp()
    local affiche
    for k, v in pairs(node) do
        affiche = Affiche.New()
        affiche:jsonRead(v)
        if affiche.getStartTime() <= nowTime and affiche.getEndTime() > nowTime then
            list:Add(affiche)
        end
    end
    list:Sort(
            function(a1, a2)
                if a1:getOrder() > a2:getOrder() then
                    return -1
                end
                if a1:getOrder() < a2:getOrder() then
                    return 1
                end
                if a1:getOrder() == a2:getOrder() then
                    if a1:getStartTime()>a2:getStartTime() then
                        return 1
                    end
                    if a1:getStartTime()<a2:getStartTime() then
                        return -1
                    end
                end
                return 0
            end)
    return list
end

--需要与后台对应
function LuaSDKHelper.toJsonNode(json)
    --TODO 转换成对应json列表
end
