---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/2 19:47
--- Lua工具

LuaUtil = {}

--获取子物体身上的组件，并做一些初始操作
function LuaUtil.GetChildComponent(uiObj,path,type)
    local component = Util.GetChildComponent(uiObj,path,type)
    --语言配置处理
    if type == ComponentName.UIText then
        local key = component.text;
        local index,e = string.find(key,'@')
        if index ==1 then
            key,e = string.gsub(key,'@','',1)
            component.text = Language[key]
        end
    end
    return component
end

--插值函数
function LuaUtil.Lerp(a,b,t)
    if t<0 then
        t = 0
    end
    if t>1 then
        t = 1
    end
    return a+(b-a)*t
end