---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/29 19:53
--- 定时器

Timer  = class("Timer")

--初始化定时器
function Timer:InitTimer(intervalTime,repeatCount)
    Log("Timer InitTimer")
    self.intervalTime = intervalTime
    self.repeatCount = repeatCount
    self.running = false
    self.count = 0
    self.nextTime = 0
    self.dispose = false
end

function Timer:AddOnTimer(action)
    self.onTimer = action
end

--定时处理
function Timer:Update(nowTime)
    if not self.running then
        return
    end
    if nowTime <self.nextTime then
        return
    end
    self.count = self.count+1
    if self.onTimer ~= nil then
        self.onTimer()
    end
    self.nextTime = nowTime + self.intervalTime
    if self.repeatCount>0 and self.count >=self.repeatCount then
        self:Stop()
    end
end
--开启
--@first 是否是首次开启
function Timer:Start(first)
    self.count = 0
    self.running = true
    self.startTime = Time.GetTimestamp()
    if first then
        self.nextTime = self.startTime
    else
        self.nextTime = self.startTime +self.intervalTime
    end
    self.dispose = false
end

--重置
function Timer:Reset()
    self.startTime = Time.GetTimestamp()
    self.nextTime = self.startTime+self.intervalTime
    self.count = 0
end

--停止定时器
function Timer:Stop()
    self.running = false
    self.startTime = 0
    self.count = 0
    self.dispose = true
end

--是否停止
function Timer:IsDispose()
    return self.dispose
end

return Timer