---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/24 22:25
---

MainWindow = class("MainWindow",UIBase)

function MainWindow:Update()
    Log("MainWindow Update")
end