---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 大杰哥.
--- DateTime: 2018/3/27 17:28
---
UIBase = class("UIBase")

--开启Update方法，请不要在UIBase中声明Update方法
function UIBase:StartUpdate()
    if self.Update ~= nil then
        if self.handle ~=nil then
            UpdateBeat:RemoveListener(self.handle)
        else
            self.handle = UpdateBeat:CreateListener(self.Update,self)
        end
        UpdateBeat:AddListener(self.handle)
    end
end

--开启FixedUpdate方法，请不要在UIBase中声明FixedUpdate方法
function UIBase:StartFixedUpdate()
    if self.FixedUpdate ~= nil then
        if self.fixHandle ~=nil then
            FixedUpdateBeat:RemoveListener(self.fixHandle)
        else
            self.fixHandle = FixedUpdateBeat:CreateListener(self.FixedUpdate,self)
        end
        FixedUpdateBeat:AddListener(self.fixHandle)
        Log("Fixed beat window name is :"..self.name)
    end
end

--开启LateUpdate方法，请不要在UIBase中声明LateUpdate方法
function UIBase:StartLateUpdate()
    if self.LateUpdate ~= nil then
        if self.lateHandle ~=nil then
            LateUpdateBeat:RemoveListener(self.lateHandle)
        else
            self.lateHandle = LateUpdateBeat:CreateListener(self.LateUpdate,self)
        end
        LateUpdateBeat:AddListener(self.lateHandle)
    end
end
--停止Update方法
function UIBase:StopUpdate()
    if self.handle~=nil then
        UpdateBeat:RemoveListener(self.handle)
    end
end
--停止FixedUpdate方法
function UIBase:StopFixedUpdate()
    if self.fixHandle~=nil then
        FixedUpdateBeat:RemoveListener(self.fixHandle)
        Log("stop Fixed beat window name is :"..self.name)
    end
end
--停止LateUpdate方法
function UIBase:StopLateUpdate()
    if self.lateHandle~=nil then
        LateUpdateBeat:RemoveListener(self.lateHandle)
    end
end

--清除update
function UIBase:ClearBeat()
    Log("UIBase clearBeat window name is:"..self.name)
    self:StopUpdate()
    self:StopFixedUpdate()
    self:StopLateUpdate()
end