---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/3/23 21:37
---打开流程1:UIManager.OpenWindow --> OnWindowAwake --> OnWindowStart （新窗口打开流程）
---打开流程2:UIManager.OpenWindow -->OnWindowStart （旧窗口打开流程）
---关闭流程1:FinishWindow-->UIManager.CloseWindow-->CloseWindow-->OnDisableWindow （关闭并缓存流程）
---关闭流程2:FinishWindow-->UIManager.CloseWindow-->CloseWindow-->OnDisableWindow-->DestroyWindow （关闭并销毁流程）
---注意：只要子类拥有相同的方法，那么将实现重载;切记不要在子类父类同时拥有相同方法时，在父类中再通过self.的形式调用子类方法
---

-- UI基础类
WindowBase = class("WindowName",UIBase)

--构造方法new()的时候调用
function WindowBase:ctor()

end


--初始化UI，只调用一次
--内部实现流程：SetUIObj-->BindWindow-->AddEventListener-->其他一次性操作
--必要时可以自己控制流程
function WindowBase:OnWindowAwake(uiObj)
    self.UIObj = uiObj
    self:OnWDAwake(uiObj)
end

--打开UI,每次窗口打开都会调用
--这里用于刷新数据
function WindowBase:OnWindowStart(param)
    self:OnWDStart(param)
end

--聚焦栈顶窗口
function WindowBase:OnFocus()
    Log("OnFocus window name :"..self.name)
end

--隐藏UI
function WindowBase:OnDisableWindow()
    self:OnDisableSubUI()
    self:ClearBeat()
    self:OnWDDisable()
end

--调用所有子UI
function WindowBase:OnDisableSubUI()
    for k, v in pairs(self.subUIs or {}) do
        v:OnDisableUI()
    end
end

--关闭UI
function WindowBase:OnCloseWindow(callback)
    self:OnWDClose()
    if callback~=nil then
        callback()
    end
end

--销毁UI
function WindowBase:OnDestroyWindow(callback)
    self:OnDestroyUI()
    self:OnWDDestroy()
    self:OnDestroySubUI()
    if callback~=nil then
        callback()
    end
end

--添加子UI
function WindowBase:AddSubUIBase(subUIBase)
    if self.subUIs == nil then
        self.subUIs = {}
    end
    self.subUIs[subUIBase.name] = subUIBase
end

--关闭自身窗口
function WindowBase:FinishWindow()
    LuaAPP.GetUIManager():CloseWindow(self.name)
end
function WindowBase:OnDestroySubUI()
    for k, v in pairs(self.subUIs or {}) do
        v:OnDestroyUI()
    end
end

--==================窗口内部流程(不得在这里实现)=====================--
function WindowBase:OnWDAwake(uiObj)
    --方法内部流程可自行控制
    --1.BindWindow()
    --2.AddEvent()
    --3.InitUI()
end

function WindowBase:OnWDStart()
end

function WindowBase:OnWDClose()
end

function WindowBase:OnWDDisable()
end

function WindowBase:OnWDDestroy()
end
--==================窗口内部流程=====================--


--UI打开动画
function WindowBase:DoShowAnimation()

end

--UI关闭动画
function WindowBase:DoCloseAnimation(callback)

end

--设置UI显示情况
function WindowBase:SetVisible(show)
    self.UIObj:SetActive(show);
end

--获取UI类型，默认普通，如有需要在子类实现相同方法
function WindowBase:GetUIType()
    return WindowType.None
end

--窗口是否是静态窗口，静态窗口在关闭时会缓存，否则直接销毁，如有需要在子类实现相同方法
function WindowBase:IsStatic()
    return true
end
--窗口层级，默认为MiddleStatic#层，如有需要在子类实现相同方法
function WindowBase:GetUILayer()
    return WindowLayer.MainLayer
end
