//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaFrameworkCore_UtilWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaFrameworkCore.Util), typeof(System.Object));
		L.RegFunction("Log", Log);
		L.RegFunction("New", _CreateLuaFrameworkCore_Util);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaFrameworkCore_Util(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaFrameworkCore.Util obj = new LuaFrameworkCore.Util();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaFrameworkCore.Util.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Log(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			LuaFrameworkCore.Util.Log(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

