---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/2 10:39
--- 语言配置表

Language = {
    ---------------公共区------------------
    str_01 = "这是语言配置表的第一句",
    str_02 = "还有第二句",
    ---------------功能区------------------
    --LoginWindow
    loginWindow_01 = "登录",
    loginWindow_02 = "账号：",
    loginWindow_03 = "密码：",
    --MainWindow
    mainWindow_01 = "首冲",
    mainWindow_02 = "每日任务",
}