---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 干冲.
--- DateTime: 2018/4/18 17:39
--- 模块相对路径

ModulePath = {
    LuaAPP = "LuaApp",

    Define = "Define/Define",
    PlayerSetting = "Define/PlayerSetting",
    GlobalDefine = "Define/GlobalDefine",
    StateStepDefine = "Define/StateStepDefine",

    UIBase = "Base/UIBase",
    WindowBase = "Base/WindowBase",
    Language = "Config/Language",

    BaseState = "State/BaseState",

    DefinitionClass = "Common/DefinitionClass",
    Timer = "Common/Timer",
    YMList = "Common/YMList",
    YMDictionary = "Common/YMDictionary",
    LuaUtil = "Common/LuaUtil",
    YMEvent = "Common/YMEvent",

    --UI相关
    Affiche = "UI/AfficheWindow/Affiche",
    --管理器
    ConfigManager ="Manager/ConfigManager",
    TimerManager = "Manager/TimerManager",
    UIManager = "Manager/UIManager",
    BackGroundManager = "Manager/BackGroundManager",

}